# sets the shell to zsh
shell /bin/zsh

# font settings
font_size 9.0

# note that this needs to be connected to the correct background 
# include ~/.cache/wal/colors-kitty.conf
background_opacity 0.45

# Monokai Vibrant colors
background #121212
foreground #F8F8F2
color0  #1c1c1c
color1  #f92672
color2  #a6e22e
color3  #fd971f
color4  #66d9ef
color5  #ae81ff
color6  #38ccd1
color7  #f8f8f2
color8  #75715e
color9  #f92672
color10 #a6e22e
color11 #fd971f
color12 #66d9ef
color13 #ae81ff
color14 #38ccd1
color15 #f9f8f5
